services:
  - type: web
    name: PasswordGeneratorApp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:5000 app:app
    envVars:
      - key: FLASK_APP
      value: app.py